export const state = {
  data: [],
  filteredData: [],
  headers: [],
  currentPage: 1,
  itemsPerPage: 20,
  currentView: "table",
  sortColumn: null,
  sortDirection: "desc",
  searchQuery: "",
  infiniteScroll: false,
  format: "spotify",
  modeFilter: "",
  statusFilter: "",
};
